version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  build-test-and-deploy:
    jobs:
      - test   #first job to run
      - build: #second job
         requires:
          - test  #its success depends on the first job       
jobs:
  test:
    docker: #
      - image: cimg/node:15.1
    steps:
      - checkout  #firstly check the changes made in the code 
      - run:
         name: install dependecies
         command: npm install

      - run:
          name: tests
          command: npm run test
  build:
    docker:
      - image: cimg/node:15.1

    steps:
      - checkout
      - run:
         name: install dependecies
         command: npm install
      - run:
          name: build production
          command: npm run build
